version: '3'
services:
  xnat-nginx:
    build:
      args:
        TIMEZONE: $TIMEZONE
    volumes:
      - ./certs/cert.crt:/etc/nginx/certs/cert.crt
      - ./certs/key.key:/etc/nginx/certs/key.key
      - ./nginx/nginx-ssl.conf:/etc/nginx/nginx.conf
  xnat-web:
    build:
      args:
        TIMEZONE: $TIMEZONE
    volumes:
      # Directory where image data is stored
      - $DATA_DIR/archive:/data/xnat/archive
      # Working and temporary store directories
      - /mnt/cache/prearchive:/data/xnat/prearchive
      - $APP_DIR/pipeline:/data/xnat/pipeline
      - $APP_DIR/build:/data/xnat/build
      - $APP_DIR/cache:/data/xnat/cache
      - $APP_DIR/ftp:/data/xnat/ftp
      # Authentication providers
      - ./auth:/data/xnat/home/config/auth
    environment:
      # Set JVM memory limits, Xmx == max memory, Xms == initial memory
      - JAVA_OPTS=-Xms${JVM_MEMGB_INIT}g -Xmx${JVM_MEMGB}g -Dxnat.home=/data/xnat/home -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000
  xnat-backup:
    build:
      args:
        TIMEZONE: $TIMEZONE
    volumes:
      - $DB_BACKUP_DIR:/backups
  xnat-db:
    build:
      args:
        TIMEZONE: $TIMEZONE
    volumes:
      - $APP_DIR/postgres:/var/lib/postgresql/data
